### ISSUE TITLE
New markdown -> AST parser engine

### ISSUE THREAD

**Issue by yaycmyk** [yaycmyk/markdown-to-jsx#31]
Not super happy with the current one, so very likely going to whip up a new one using `jison` or something of the like. It'll be a major semver change, but with it will we be able to natively handle real HTML, so :tada: (block *and* inline.)

Please comment here if any flavors beyond GFM are important to you.

**Comment by yaycmyk** [comment]
@alansouzati I believe you're the only dependent right now of this with Grommet - is GFM the extent of what you need right now?

**Comment by alansouzati** [comment]
I don't have any additional need apart from what is present today. This library is being used as the default markdown parser engine for Grommet as it is now allowing for custom components and properties.

As long as this feature remains in the library I'm all for investigating jison as a new parser for your library.
I guess you are planning to release v3.0.0 ? Let me know how I can help

**Comment by yaycmyk** [comment]
@alansouzati Yes exactly, and I have my full test suite to maintain feature parity. Just switching out the AST engine under the hood so we can do more in the future.
