### ISSUE TITLE
Support for custom JSX components and props

### ISSUE THREAD

**Issue by alansouzati** [yaycmyk/markdown-to-jsx#4]
First of all, very good job in this library. I really like the way you structured your code, it is easy to read.

Well, I'm working in a framework called Grommet (grommet.io) and I'm planning to use your library to parse a body of a blog post (markdown) to JSX. I've quickly tested your engine and generally it works as expected.

Although I was hoping to have a little bit of control over the JSX components that are being created.

For example, my framework provides an `Anchor` component that I would like to use instead of the default `a`. Also I would like to send custom props to whatever JSX component inside the AST. In the context of the anchor, I would like to send an onClick prop so that I can avoid page refresh for my single page app.

As an example this is what I hoping to get:

Markdown

```markdown

This is a general text with a [link](http://grommet.io) on it
```

JSX

```javascript
<Paragraph size="large">
  This is a general text with a <Anchor href="http://grommet.io" onClick={...}>link</Anchor> on it
</Paragraph>
```

So, I thought about augmenting your options to receive these properties, for example:

```javascript
import Paragraph from 'grommet/component/Paragraph';
import Anchor from 'grommet/component/Anchor';

converter(post.content, {
  nodeType: {
    paragraph: {
      component: Paragraph,
      props: {
        size="large"
      }
    },
    link: {
      component: Anchor,
      props: {
        onClick: function (event) {
          event.preventDefault();
          history.push('/somewhere');
        }
      }
    }
  }
})
```

Although initially it seems something needed only for my project, I believe it could be an extension of your library that others can leverage. So, if you agree with this, I can send a Pull Request with these changes. If not I can fork your project and do that on my end.

Looking forward to hearing back from you...

**Comment by yaycmyk** [comment]
Interesting use case! Let me think on this briefly and I'll figure out a way to support what you're asking for - I think the modularity makes a lot of sense.

**Comment by alansouzati** [comment]
I will send a pull request for you to look at it, just in case it helps in your thinking process.

**Comment by yaycmyk** [comment]
Supported added in `2.0.0`. Thanks for contributing!
