### ISSUE TITLE
Support custom JSX components?

### ISSUE THREAD

**Issue by KyleAMathews** [yaycmyk/markdown-to-jsx#88]
E.g. in a markdown blog post you want to add some sort of interactive widget.

```markdown
# My sweet post

Some interesting content.

<MyInteractiveWidget
  sound={false}
/>
```

My thought is that these custom components would be automatically resolved e.g. look first in the same directory and then next in an optional global component directory you setup in the converter. I need the auto resolving for Gatsby (where I want to add support for this) so that people can just drop this into a project and it just kinda works.

Thoughts?

Also... I'm investigating this for [Gatsby](https://github.com/gatsbyjs/gatsby) — so I'd want the conversion to happen at build time not run time. I don't see any easy way to convert things? Perhaps you do? Perhaps I need to fork this project to convert it to building a string of `React.createElements`.

**Comment by yaycmyk** [comment]
Hmm. This component is also meant to work in the browser, so traversing the file system is probably not in the cards. One caveat is I'm using remark under the hood, so if its HTML parser rejects the custom components, there's not much I can do short of reimplementing that whole part of the system.

Anything that looks like HTML is generally regarded as an antipattern in markdown land. One thing I might suggest is using fenced code blocks and maybe eval-ing their content if marked with a custom "lang" of your choosing. Interesting, but tough problem to solve for what is intended to be a pretty opinionated format.

**Comment by yaycmyk** [comment]
@KyleAMathews on your second point, is the idea to basically create a stringified version of the nested calls that could be its own exported module? Sort of precompiling in a sense...
